### ISSUE TITLE
Running python file display "ValueError: auth_key must not be empty"

### ISSUE THREAD

**Issue by prog-amateur2** [DeepLcom/deepl-python#31]
Hello, following the issue #23 , I have a similar error when I use deepl-python in a Flask python file (this is a Flask mini-server for a web application). 

## Context :
My DeepL account is a free one with access to the DeepL REST API

![Screenshot from 2022-04-07 13-29-07](https://user-images.githubusercontent.com/60101083/162190710-d813a362-f4e8-4c0e-9a09-e7545b194137.png)

Each time I connect to my account, I have the following error pop-up : 
![Screenshot from 2022-04-07 13-28-45](https://user-images.githubusercontent.com/60101083/162191077-9d970869-994a-40eb-93f4-eea060f33dcc.png)

When I run the python file with the authorization key into it, I can't open it because of the following error : 

```
Traceback (most recent call last):
  File "~/app_2.py", line 22, in <module>
    translator = deepl.Translator(os.getenv('xxx-xxx-xxx-xxx-xxx'))
  File "~/.local/lib/python3.10/site-packages/deepl/translator.py", line 429, in __init__
    raise ValueError("auth_key must not be empty")
ValueError: auth_key must not be empty
```

As you can see, I use my key like for example `abc-5ea-0cb-...` without the prefix `auth-key=`

Something strange : I can use my authorization key in a terminal like below : 

```
>>> python3 -m deepl --auth-key=xxx-xxx-xxx-xxx-xxx-xxx text --to=FR "Text to be translated."
>>> Texte à traduire
```

## Questions :

1. Could you please confirm I use my authorization key the right way ? 
2. If so, could you please tell me how to solve my issue ? 

Thank you very much for your kind help !

**Comment by prog-amateur2** [comment]
Hello, using : 
```
os.environ['API_KEY'] = 'xxxxxxxxxxxxxxxxxxxxxxxx'
translator = deepl.Translator(os.getenv('API_KEY'))
```
does work, I don't know why. So, could you check and if yes, we can close this issue, thank you very much !

**Comment by daniel-jones-deepl** [comment]
Hi @prog-amateur2, it seems your key is fine.
In the readme, we recommend storing your authentication key in an environment variable, and then read the auth key from the variable in your script. However we did not explain how to store the key.
In your second message above, the `os.environ['API_KEY'] = ...` line is storing to the environment variable, and `os.getenv` reads from the variable.

This is overly complex, sorry for the confusion. You can simplify and combine both lines to:
```translator = deepl.Translator('xxxxxxxxxxxxxxxxxxxxxxxx')```
We're going to simplify our readme example to something like this in our next update.
