### ISSUE TITLE
ModuleNotFoundError during Poetry Installation in Ubuntu 22.04 

### ISSUE THREAD

**Issue by FOehlschlaeger** [DeepLcom/deepl-python#47]
Hello there, 

after forking and cloning of the repository, I was trying to install the dependencies for modification of the source code based on the README file. I was using a virtual machine with Ubuntu 22.04 LTS, but I got an error related to a missing module `CacheControl`. Probably it is related to Ubuntu 22.04 and the poetry installation regarding to this [bug report](https://bugs.launchpad.net/ubuntu/+source/poetry/+bug/1958227). The fix would be to install `CacheControl` via `sudo apt install python3-cachecontrol`.

Maybe, this can be added as remark to the installation section in the README file? 

Here is the traceback after executing of `poetry install`:
```shell
Traceback (most recent call last):
  File "/usr/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/usr/lib/python3/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/lib/python3/dist-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/usr/lib/python3/dist-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/usr/lib/python3/dist-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/usr/lib/python3/dist-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/usr/lib/python3/dist-packages/poetry/repositories/pypi_repository.py", line 11, in <module>
    from cachecontrol import CacheControl
ModuleNotFoundError: No module named 'cachecontrol'
```

Hopefully, I provided enough information, otherwise let me know. This is my first issue and participation in open source, so please feel free to give me any feedback.

**Comment by daniel-jones-deepl** [comment]
Hi @FOehlschlaeger Friso, thanks for creating this issue, and welcome to open source 😄 

I think you're right: it seems to be an issue with either Ubuntu 22.04 or Poetry. Thanks for the PR.
