### ISSUE TITLE
Is there anyway to check which line caused error when translating document?

### ISSUE THREAD

**Issue by leminhyen2** [DeepLcom/deepl-python#6]
I have this error which I suspect is due to the format of a few lines in my text file. But this error is very cryptic so there is no way for me to check what caused it. 

Traceback (most recent call last):
  File ".\testDeepL.py", line 7, in <module>
    translator.translate_document_from_filepath(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 774, in translate_document_from_filepath
    raise e
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 764, in translate_document_from_filepath
    self.translate_document(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 803, in translate_document
    handle = self.translate_document_upload(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 858, in translate_document_upload       
    self._raise_for_status(status, content, json)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 479, in _raise_for_status
    raise DeepLException(f"Bad request{message}")

**Comment by daniel-jones-deepl** [comment]
Hi @leminhyen2,

You are right, exception tracebacks are difficult to understand without looking into the code. However if you catch the exception and inspect the message, you should see a simpler message (for example "Bad request, message: Invalid file data." would confirm your suspicion):
```
try:
    # Your code
except DeepLException as e:
    errorMessage = str(e)
    print(errorMessage)
```
If you share the error message I might be able to help further.

**Comment by leminhyen2** [comment]
This is my code:
try:
    translator.translate_document_from_filepath(
        "test.txt",
        source_lang="JA",
        target_lang="EN-US",
        output_path="result.txt"
    )
except DeepLException as e:
    errorMessage = str(e)
    print(errorMessage)

Traceback (most recent call last):
  File ".\testDeepL.py", line 8, in <module>
    translator.translate_document_from_filepath(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 774, in translate_document_from_filepath
    raise e
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 764, in translate_document_from_filepath
    self.translate_document(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 803, in translate_document
    handle = self.translate_document_upload(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 858, in translate_document_upload       
    self._raise_for_status(status, content, json)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deepl\translator.py", line 479, in _raise_for_status
    raise DeepLException(f"Bad request{message}")
deepl.exceptions.DeepLException: Bad request, message: Invalid file data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\testDeepL.py", line 14, in <module>
    except DeepLException as e:
NameError: name 'DeepLException' is not defined

**Comment by daniel-jones-deepl** [comment]
Ok the line `deepl.exceptions.DeepLException: Bad request, message: Invalid file data.` confirms that there is an issue with the file content. You could try with a simpler file first, for example just a text file containing "Hello, world!".

There is another long exception backtrace because I assumed you would have `import deepl` in your code. To fix that and get a nicer message, use `except Exception as e:` instead of `except DeepLException as e:`

**Comment by leminhyen2** [comment]
I did have `import deepl` though

import deepl

# Create a Translator object providing your DeepL API authentication key
translator = deepl.Translator("65ca6737-4333-a78d-dabf-e84e6d5f269b:fx")

# Translate a formal document from English to German 
try:
    translator.translate_document_from_filepath(
        "test.txt",
        source_lang="JA",
        target_lang="EN-US",
        output_path="result.txt"
    )
except Exception as e:
    errorMessage = str(e)
    print(errorMessage)

Here is the supposedly better log:
`Bad request, message: Invalid file data.`

If there is no other way to debug which line caused the issue. You can close this issue.
My file has around 57k lines and I have a 500k characters limit (not sure if this can be the issue)
But it does iterated a a few lines because I saw the word usage went up but no result

**Comment by leminhyen2** [comment]
I accidentally put my API key so can you give me a reply that you saw the message then I'll delete my reply

**Comment by daniel-jones-deepl** [comment]
Okay you can delete your message, or just regenerate an API key on your account page.

**Comment by leminhyen2** [comment]
ok

**Comment by daniel-jones-deepl** [comment]
Sorry that was a mistake from me. Even with the `import deepl`, it should be `except deepl.DeepLException as e:`.

Anyway, this error message is showing the response from the server. Unfortunately right now there is no more detailed information, for example on which line the error occurred. 

You could instead try translate the file in smaller pieces using `translate_text()`.

**Comment by leminhyen2** [comment]
Thank you, I'll do that instead
