### ISSUE TITLE
Exception ignored in: <function Translator.__del__ at 0x7fb336445b80>

### ISSUE THREAD

**Issue by zoobereq** [DeepLcom/deepl-python#73]
Hello, 

The API works great but after the translation is generated, I'm getting the following:

>>>
Exception ignored in: <function Translator.__del__ at 0x7fb336445b80>
Traceback (most recent call last):
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/deepl/translator.py", line 506, in __del__
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/deepl/translator.py", line 713, in close
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/deepl/http_client.py", line 91, in close
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 747, in close
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 325, in close
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/Users/littlezub/opt/anaconda3/lib/python3.9/site-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable

Any advice would be appreciated.

**Comment by JanEbbing** [comment]
Hi, which version of the DeepL library, `requests` and `urllib3` do you have installed in that environment?

**Comment by zoobereq** [comment]
Hi, and sorry of the delayed reply.  Here's the requested info:
- DeepL v. 1.14.0
- requests v. 2.26.0
- urllib3 v. 1.26.7
Hope this helps.

**Comment by velochy** [comment]
Ran into the same issue. Problem is the urllib v. 1.26.7, as deepl expects v2. 
In my case, the old urllib is due to s3fs, which does not work with the new urllib, so it's a sticky situation, but not one of deepl.
